#! /bin/tcsh -f

foreach a ( $argv)

foreach x (0 1 2 3 4)

src/seq2inp SMM/$a/c00$x | grep -v "#" > sp_c00$x
src/seq2inp -bl SMM/$a/c000 | grep -v "#" > b_c00$x

src/seq2inp SMM/$a/f00$x | grep -v "#" > sp_f00$x
src/seq2inp -bl SMM/$a/f000 | grep -v "#" > b_f00$x

src/nnbackprop -nh 10 -tf sp_c00$x -syn sp_syn_dat_$x sp_f00$x > /dev/null
src/nnbackprop -nh 10 -tf b_c00$x -syn b_syn_dat_$x b_f00$x > /dev/null


echo "NN\t$a\t$x"
src/nnforward -s sp_syn_dat_$x  sp_c00$x | grep -v "#" | gawk '{print $1,$3}' | src/xycorr | gawk '{OFS = "\t" ; print $5,$7}'

echo "NN Blosum\t$a\t$x"
src/nnforward -s b_syn_dat_$x  b_c00$x | grep -v "#" | gawk '{print $1,$3}' | src/xycorr | gawk '{OFS = "\t" ; print $5,$7}'

rm sp_c00$x
rm b_c00$x
rm sp_f00$x
rm b_f00$x
rm sp_syn_dat_$x 
rm b_syn_dat_$x 

end
end
